/* Base16 Rofi Theme */
/* This file is autogenerated by the apply-theme script */

* {
    bg:     ${THEME_BASE00};
    cur:    ${THEME_BASE01};
    fgd:    ${THEME_BASE05};
    cmt:    ${THEME_BASE03};
    cya:    ${THEME_BASE0C};
    grn:    ${THEME_BASE0B};
    ora:    ${THEME_BASE09};
    pur:    ${THEME_BASE0E};
    red:    ${THEME_BASE08};
    yel:    ${THEME_BASE0A};
}
